language: python
python:
  - "3.6"
install:
  - python setup.py install

deploy:
  provider: pypi
  user: mmaia.cc
  password:
    secure: tLTN9AoU7yoFJt7uRqsfOyp6VPM2mVw6LX9sTeldOqhnFXxOrWnXzH3QMxi072TJIYyM+4rh3ButECGtTR5IKOSA7FTmeY2A5sy0Fo0toNY1mKXnij80byZkymMXBmZGFK11wCM8u7m5dx1dgxyNcmMv4C2A9nuygDTwfJf90ft+bf3cLMI7n4R95UJKyQ4uEMrlUFNK95wQUgiaU0wdYRsSDEkg6EXDh+XEWgMQnm1AsS778Q+Aiz7A4JOVHF63ycWDeFKyCLraEBGd7o0rxHSddYxD+ks7FNscHfHqzWnwkl4G2B18gGfXM0MuF0aB6HJVsNbTJOeiK8Yj+dhqivrKKpPcbolmccBnuSKI9fNKsoloVWs5XOh7W3DUnS1uYf1huEcSG7UUBoDLMImmZLPIVJx8/Cy2BYDMOEaRgaOPD6jkvyTeik83qQoou2BWmMbXfIUyozZ3ePBlk/2n+uXWnV0TpgTHqVotk/v8adldlPbaKGGOEBJgypICmQgTfBQCyCvaf19DdrSuDVhirmsI2zEkIVLJS9GvwRD4rf7JZgxK/HoNrYYtHSKk3f1yzZ9L4/cgEtyIeaWlQrVqMLL/54AJqxWKO3gFj8c3BdcoAabzFwqKNlCWLvh1JsNVksCkpNSUjH0m6lMw2Q7VftH3zp3dYn7p6PSqDW1N7Js=
  on:
    branch: master
