version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    environment:
      CC_TEST_REPORTER_ID: $CC_TEST_REPORTER_ID
    docker:
      - image: circleci/python:3.7
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - python/install-packages:
          args: install --dev
          pkg-manager: pipenv
      - run:
          command: pipenv run pytest
          name: Test
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter after-build

workflows:
  main:
    jobs:
      - build-and-test

