import os

AMZ_STORE_NAME = os.getenv('AMZ_STORE_NAME')
BW2_AFL_ID = os.getenv('BW2_AFL_ID')
AFILIO_AFFID = os.getenv('AFILIO_AFFID')
AFILIO_TOKEN = os.getenv('AFILIO_TOKEN')
AFILIO_SITE_ID = os.getenv('AFILIO_SITE_ID')
MGZ_STORE_NAME = os.getenv('MGZ_STORE_NAME')
NATURA_CONSULTORIA_NAME = os.getenv('NATURA_CONSULTORIA_NAME')
BANGGOOD_REFERENCE_ID = os.getenv('BANGGOOD_REFERENCE_ID')
LOMADEE_SOURCE_ID = os.getenv('LOMADEE_SOURCE_ID')
ZANOX_ADS_SPACE_ID = os.getenv('ZANOX_ADS_SPACE_ID')
ZANOX_CONNECT_ID = os.getenv('ZANOX_CONNECT_ID')
HURB_CMP_ID = os.getenv('HURB_CMP_ID')

afilio_programs = {
    "walmart.com.br": 191,
    "polishop.com.br": 357,
    "centauro.com.br": 382,
    "latam.com": 483,
    "nespresso.com": 1968,
    "shopfato.com.br": 573,
    "netshoes.com.br": 577,
    "cvc.com.br": 610,
    "mobly.com.br": 764,
    "pontofrio.com.br": 768,
    "extra.com.br": 769,
    "casasbahia.com.br": 770,
    "rihappy.com.br": 928,
    "fastshop.com.br": 994,
    "submarino.com.br": 1008,
    "shoptime.com.br": 1009,
    "americanas.com.br": 1010,
    "oqvestir.com.br": 1086,
    "epocacosmeticos.com.br": 1102,
    "thebeautybox.com.br": 1123,
    "lojaskd.com.br": 1134,
    "cantao.com.br": 1171,
    "posthaus.com.br": 1187,
    "livrariacultura.com.br": 1190,
    "onofreagora.com.br": 1222,
    "wine.com.br": 1225,
    "boticario.com.br": 1255,
    "hopelingerie.com.br": 1260,
    "eudora.com.br": 1318,
    "supermuffato.com.br": 1326,
    "quemdisseberenice.com.br": 1329,
    "megamamute.com.br": 1509,
    "offpremium.com.br": 1534,
    "fyistore.com.br": 1536,
    "animale.com.br": 1537,
    "ikesaki.com.br": 1606,
    "divvino.com.br": 2459,
    "divinoamor.com.br": 1601,
    "natura.com.br": 1604,
    "pontofrioatacado.com.br": 1619,
    "trocafone.com": 1672,
    "cea.com.br": 1678,
    "balaodainformatica.com.br": 1681,
    "afabula.com.br": 1701,
    "maccosmetics.com.br": 2253,
    "onofre.com.br": 1719,
    "madeiramadeira.com.br": 1885,
    "colombo.com.br": 1739,
    "emporio.com": 1754,
    "emporiodacerveja.com.br": 1754,
    "zattini.com.br": 1785,
    "shopfacil.com.br": 1796,
    "sephora.com.br": 1926,
    "mercatto.com.br": 1830,
    "chicorei.com": 1944,
    "taqi.com.br": 1950,
    "friboi.com.br": 1951,
    "bobstore.com.br": 1959,
    "carrefour.com.br": 2829,
    "korresbr.com.br": 2628,
    "loja.jequiti.com.br": 2495,
    "centralar.com.br": 2168,
    'banggood.com': 2693,
    "pt.aliexpress.com": 2351,
    "aliexpress.com": 2351,
}

LOMADEE_ACCEPTED_DOMAINS = ['maxmilhas.com', 'aramis.com.br', 'novaconcursos.com.br', 'dermage.com.br',
                            'clubemarisol.com',
                            'pt.newchic.com', 'semparar.comassine-promo', 'tabaratotolevando.comcomprar', 'banggood',
                            'catho.comeducacao', 'escalaverde.com.br', 'seja-lev', 'vestibulares.comanhanguera',
                            'vestibular.unoparead.com', 'bugshop.com', 'seubebeprecisa.com.br', 'reppara.com',
                            'estude-ipemigpos-ead', 'cerejasembolo.com', 'pipocaweb.com', 'aureanutrition.com.br',
                            'loja.betec.com', 'zandarastore.com', 'tf.com', 'magazinepagmenos.com', 'segundociclo.com',
                            'descomplica.com', 'colorbrinque.com', 'lojadomecanico.com.br', 'camisariacolombo.com',
                            'amazon.com',
                            'loja.asus.com', 'americanas.com', 'americanas.com.br', 'nike.com', 'netshoes.com.br',
                            'centauro.com',
                            'loja.electrolux.com.br', 'novomundo.com', 'loja.brastemp.com.br', 'pbkids.com',
                            'pagseguro.uol.com', 'travessa.com', 'lomadee.com', 'shoptime.com', 'hangloose.com',
                            'girafa.com.br', 'girafa.com',
                            'mobly.com', 'submarino.com', 'submarino.com.br', 'lenovobr', 'rihappy.com',
                            'livrariacultura.com',
                            'abouthome.com.br',
                            'loja.consul.com', 'classictennis.com', 'sieno.com', 'zattini.com', 'br.aliexpress',
                            'natue.com.br',
                            'maniapop.com', 'drogariasaopaulo.com', 'drogariaspacheco.com', 'leveros.com.br',
                            'lojamultilaser.com', 'pneustore.com.br', 'chicorei', 'gearbest', 'schumann.com',
                            'flytappt-br',
                            'tng.com', 'jocar.com.br', 'nextel.com', 'repassa.com.br', 'portosegurofaz.com',
                            'meuquantum.com.br', 'loja.meupositivo.com.br', 'valejet', 'beline.com.br',
                            'loja.br.vaio.com',
                            'inboxshoes.com.br', 'hermosocompadre.com.br', 'malwee.com.br', 'parperfeito.comcpx',
                            'centralar.com.br', 'dresslily.com', 'pt.zaful', 'pierrecardin.com', 'millacabelos.com',
                            'clubepaladar.com', 'iridiumlabs.com.br', 'store.pierrecardin.com', 'donacoelha.com',
                            'irobotloja.com', 'ankeroficial.com', 'nutribulletbrasil.com', 'mmplace.com', 'mirage.com',
                            'lojaweego.com ', 'fata.com.br', 'friopecas.com.br', 'kitchenaid.com.br', 'mrdeal.com.br',
                            'passagensaereas.com', 'editorafoco.com.br', '2amgaming', 'zonacerealista.com',
                            'resultadosdigitais', 'nathusbrasil.com', 'darksidebooks.com.br', 'elare.com.br',
                            'kitled.com.br',
                            'cliquebemestar.com', 'startech.com', 'stoodi.com.br', 'koralle.com.br', 'ordenato.com.br',
                            'viacaoouroeprata.com.br', 'gazin.com', 'vitalatman.com.br', 'veni.com',
                            'ribsolenergiasolar.com.br', 'natufibras.com.br', 'almundo.com.br', 'boxviva.com.br',
                            'amendoasconfeitadas.com.br', 'hostinger.com.br', 'bralingerie.com.br', 'recco.com.br',
                            'cabanamagazine.com', 'klin.com.br', 'nuuvem', 'uitech.com.br', 'cartersoshkosh.com',
                            'doceerva.com', 'barcelopt', 'joico.com', 'hipervarejo.com', 'lojablowback.com',
                            'rzmshop.com',
                            'impacta', 'altogiro.net/', 'vibracomigo.com', 'organomix.com.br', 'swift.com.br',
                            'sosolingerie.com', 'ultrabikes.com', 'ultrasports.com.br', 'enebabr', 'deans.com',
                            'cpmoffice.com.br', 'gymchef.com ', 'gourmetzinhocomidinhas.com', 'usaflex.com',
                            'maisbaratostore.com.br', 'grupoa.com', 'yori.store/', 'loja.cartaoanimal.com',
                            'suplementosmaisbaratos', 'etna.com', 'chicbest.com', 'shoponline.iorane.com',
                            'lojadocafe.com',
                            'cavuca.com.br', 'santorioficial.com', 'zalikacosmeticos.com', 'plantei.com',
                            'multikidsbaby.com',
                            'lojamultikids.com', 'atrioesportes.com', 'pulsesound.com', 'arenawarrior.com',
                            'shoprvx.com.br',
                            'oferta-dental', 'samsclub', 'nordvpnpt-br', 'notetec.com', 'finanzero.com',
                            'reservacool.com.br',
                            'leiturinha.com', 'levok.com', 'hfbrazil.com', 'uniformulaonline.com',
                            'positivocasainteligente.com', 'comix.com', 'usecamisetas', 'pollia.com', 'foundit.com',
                            'conoycosmetics', 'megatonsuplementos.com', 'latifundio.com.br', 'guitarpedia.com',
                            'mobiliata.com',
                            'homeis.com', 'magrelashop.com', 'bugalupa.com', 'eletroalmeida.com',
                            'livrariaflorence.com',
                            'vitrinecasual.com.br', 'volcom.com', 'vissla.com', 'vhita.com', 'quintadellarte.com',
                            'mundoinfantilstore.com', 'viggore.com', 'health-pet-seguro', 'loja.alfaparfmilano.com',
                            'lojauniversokids', 'ciclic.com', 'e-cotaseguroauto', 'newbeach.com',
                            'centerbikemaringa.com.br',
                            ]
