import os

AMZ_STORE_NAME = os.getenv("AMZ_STORE_NAME")
BW2_AFL_ID = os.getenv("BW2_AFL_ID")
AFILIO_AFFID = os.getenv("AFILIO_AFFID")
AFILIO_TOKEN = os.getenv("AFILIO_TOKEN")
AFILIO_SITE_ID = os.getenv("AFILIO_SITE_ID")
MGZ_STORE_NAME = os.getenv("MGZ_STORE_NAME")
NATURA_CONSULTORIA_NAME = os.getenv("NATURA_CONSULTORIA_NAME")
BANGGOOD_REFERENCE_ID = os.getenv("BANGGOOD_REFERENCE_ID")
LOMADEE_SOURCE_ID = os.getenv("LOMADEE_SOURCE_ID")
ZANOX_ADS_SPACE_ID = os.getenv("ZANOX_ADS_SPACE_ID")
ZANOX_CONNECT_ID = os.getenv("ZANOX_CONNECT_ID")
HURB_CMP_ID = os.getenv("HURB_CMP_ID")
FASTSHOP_AFL_ID = os.getenv("FASTSHOP_AFL_ID")
FASTSHOP_AFL_SELLER_NAME = os.getenv("FASTSHOP_AFL_SELLER_NAME")

afilio_programs = {
    "walmart.com.br": 191,
    "polishop.com.br": 357,
    "centauro.com.br": 382,
    "latam.com": 483,
    "nespresso.com": 1968,
    "shopfato.com.br": 573,
    "netshoes.com.br": 577,
    "cvc.com.br": 610,
    "mobly.com.br": 764,
    "pontofrio.com.br": 768,
    "extra.com.br": 769,
    "casasbahia.com.br": 770,
    "rihappy.com.br": 928,
    "fastshop.com.br": 994,
    "submarino.com.br": 1008,
    "shoptime.com.br": 1009,
    "americanas.com.br": 1010,
    "oqvestir.com.br": 1086,
    "epocacosmeticos.com.br": 1102,
    "thebeautybox.com.br": 1123,
    "lojaskd.com.br": 1134,
    "cantao.com.br": 1171,
    "posthaus.com.br": 1187,
    "livrariacultura.com.br": 1190,
    "onofreagora.com.br": 1222,
    "wine.com.br": 1225,
    "boticario.com.br": 1255,
    "hopelingerie.com.br": 1260,
    "eudora.com.br": 1318,
    "supermuffato.com.br": 1326,
    "quemdisseberenice.com.br": 1329,
    "megamamute.com.br": 1509,
    "offpremium.com.br": 1534,
    "fyistore.com.br": 1536,
    "animale.com.br": 1537,
    "ikesaki.com.br": 1606,
    "divvino.com.br": 2459,
    "divinoamor.com.br": 1601,
    "natura.com.br": 1604,
    "pontofrioatacado.com.br": 1619,
    "trocafone.com": 1672,
    "cea.com.br": 1678,
    "balaodainformatica.com.br": 1681,
    "afabula.com.br": 1701,
    "maccosmetics.com.br": 2253,
    "onofre.com.br": 1719,
    "madeiramadeira.com.br": 1885,
    "colombo.com.br": 1739,
    "emporio.com": 1754,
    "emporiodacerveja.com.br": 1754,
    "zattini.com.br": 1785,
    "shopfacil.com.br": 1796,
    "sephora.com.br": 1926,
    "mercatto.com.br": 1830,
    "chicorei.com": 1944,
    "taqi.com.br": 1950,
    "friboi.com.br": 1951,
    "bobstore.com.br": 1959,
    "carrefour.com.br": 2829,
    "korresbr.com.br": 2628,
    "loja.jequiti.com.br": 2495,
    "centralar.com.br": 2168,
    "banggood.com": 2693,
    "pt.aliexpress.com": 2351,
    "aliexpress.com": 2351,
}

LOMADEE_ACCEPTED_DOMAINS = [
    "natue.com.br",
    "newbalance.com.br",
    "lepostiche.com.br",
    "deans.com.br",
    "usaflex.com.br",
    "loja.grupoa.com.br",
    "rioquente.com.br",
    "positivocasainteligente.com.br",
    "imperiodosquadros.com.br",
    "descomplica.com.br",
    "lojadrdog.com.br",
    "lojashure.com.br",
    "belezharia.com.br",
    "casadosparafusosfranca.com.br",
    "loja.agapemoda.com.br",
    "amoberloque.com.br",
    "costadosauipe.com.br",
    "modab.com.br",
    "timelinebrasil.com.br",
    "lineaalimentos.com.br",
    "macrolub.com.br",
    "loja.rovitex.com.br",
    "integralmedica.com.br",
    "minhaitatiaia.com.br",
    "amazon.com.br",
    "americanas.com.br",
    "nike.com.br",
    "netshoes.com.br",
    "loja.electrolux.com.br",
    "brastemp.com.br",
    "decathlon.com.br",
    "pbkids.com.br",
    "pagseguro.uol.com.br",
    "travessa.com.br",
    "lomadee.com",
    "playeduca.com.br",
    "ferramentaskennedy.com.br",
    "br.loccitane.com",
    "carrefour.com.br",
    "shoptime.com.br",
    "girafa.com.br",
    "mobly.com.br",
    "submarino.com.br",
    "lenovo.com",
    "rihappy.com.br",
    "peixeurbano.com.br",
    "livrariacultura.com.br",
    "loja.consul.com.br",
    "sieno.com.br",
    "zattini.com.br",
    "cea.com.br",
    "targus.com.br",
    "chefsclub.com.br",
    "clubedomalte.com.br",
    "allbags.com.br",
    "kipling.com.br",
    "br.loccitaneaubresil.com",
    "maniapop.com.br",
    "chicorei.com",
    "eletrum.com.br",
    "jansport.com.br",
    "gearbest.com",
    "flytap.com",
    "br.diesel.com",
    "jocar.com.br",
    "repassa.com.br",
    "aramis.com.br",
    "portosegurofaz.com.br",
    "loja.meupositivo.com.br",
    "beline.com.br",
    "loja.br.vaio.com",
    "brazil.coach.com",
    "malwee.com.br",
    "parperfeito.com.br",
    "samsonite.com.br",
    "millacabelos.com.br",
    "donacoelha.com",
    "anker.com.br",
    "relogiosdefabrica.com.br",
    "passagensaereas.com.br",
    "editorafoco.com.br",
    "2amgaming.com",
    "resultadosdigitais.com.br",
    "nathusbrasil.com.br",
    "elare.com.br",
    "kitled.com.br",
    "despachantedok.com.br",
    "stoodi.com.br",
    "koralle.com.br",
    "ordenato.com.br",
    "viacaoouroeprata.com.br",
    "vitalatman.com.br",
    "veni.com.br",
    "soparaorganizar.com.br",
    "ribsolenergiasolar.com.br",
    "boxviva.com.br",
    "hostinger.com.br",
    "montink.com.br",
    "bralingerie.com.br",
    "recco.com.br",
    "cabanamagazine.com.br",
    "nuuvem.com",
    "cartersoshkosh.com.br",
    "joico.com.br",
    "hipervarejo.com.br",
    "lojablowback.com.br",
    "rzmshop.com.br",
    "impacta.com.br",
    "clubemarisol.com.br",
    "clubeorganico.com",
    "swift.com.br",
    "eneba.com",
    "cpmoffice.com.br",
    "pt.newchic.com",
    "trazpraca.com",
    "tabaratotolevando.com.br",
    "etna.com.br",
    "iorane.com.br",
    "zalikacosmeticos.com.br",
    "plantei.com.br",
    "oferta-dental.com",
    "nordvpn.com",
    "levok.com.br",
    "hfbrazil.com.br",
    "comix.com.br",
    "banggood.com",
    "detoxsuper.com.br",
    "foundit.com.br",
    "conoycosmetics.com",
    "latifundio.com.br",
    "homeis.com.br",
    "magrelashop.com.br",
    "anhanguera.com",
    "vestibulares.com.br",
    "livrariaflorence.com.br",
    "vhita.com.br",
    "aprilbrasil.com.br",
    "reppara.com.br",
    "mundodasartes.com.br",
    "estude-ipemig.com",
    "pipocaweb.com.br",
    "petitlouarth.com.br",
    "ciclic.com.br",
    "loja.betec.com.br",
    "magazinepagmenos.com.br",
    "mamorena.com.br",
    "primehomedecor.com.br",
    "segundociclo.com.br",
    "descomplica.com.br",
    "colorbrinque.com.br",
    "portodeletras.com.br",
    "usebunker.com.br",
    "travelmobile.biz",
    "barbaderespeito.com.br",
    "assine-abril.com",
    "grupoeditorialzit.com.br",
    "drogarialiviero.com.br",
    "foreo.com",
    "goreadassineabril.com",
    "corpoesuplemento.com.br",
    "pozelar.com.br",
    "luccofit.com.br",
    "quisty.com.br",
    "unesul.com.br",
    "siberiano.com.br",
    "lojasmm.com",
    "leonfershop.com.br",
    "liberatti.com.br",
    "macbuystore.com.br",
    "columbiasportswear.com.br",
    "lackto.com.br",
    "colchoesemma.com.br",
    "carinhosokids.com.br",
    "universoenfim.com.br",
    "officina7.com.br",
    "descomplica.com.br",
    "oferbox.site",
    "lelupets.com.br",
    "sofaemesa.com.br",
    "twosexxy.com.br",
    "catzcalcados.com.br",
    "avenida.com.br",
    "outletclass.com.br",
    "relaxmedic.com.br",
    "lojameu.com",
    "natulha.com.br",
    "basicamente.com",
    "nautikalazer.com.br",
    "samatec.com.br",
    "acessoshop.com.br",
    "empresas.festaeagora.com.br",
    "celular-vivo.com",
    "clubedomel.com.br",
    "fom.com.br",
    "lojavasart.com.br",
    "wondershare.com",
    "lojasrenner.com.br",
    "fitmania.com.br",
    "meubmg.com.br",
    "vejacalcados.com.br",
    "farmadelivery.com.br",
    "vivabeauty.com.br",
    "palaciodasferramentas.com.br",
    "mahogany.com.br",
    "autoz.com.br",
    "desembala.com.br",
    "divinalu.com.br",
    "aprovacursos.com.br",
    "wallsgeneralstore.com.br",
    "annyjalecos.com",
    "musicfriends.com.br",
    "vendesk.com",
    "saudegarantida.com.br",
    "projectcompany.org",
    "lgbt.rio.br",
    "farmaciaindiana.com.br",
    "buddhaspa.com.br",
    "berlanda.com.br",
    "lacadordeofertas.com.br",
    "lobella.com.br",
    "meritocomercial.com.br",
    "lojasmarkem.com.br",
    "tiffjoias.com.br",
    "dogfriendsforever.com.br",
    "lojaietec.commercesuite.com.br",
    "aveovision.com.br",
    "oscarcalcados.com.br",
    "loja.sinestese.com.br",
    "souvie.com.br",
    "loja.karcher.com.br",
    "clickclass.com.br",
    "elevelife.com.br",
    "loja.madesa.com",
    "contratetim.com.br",
    "papelarte.com.br",
    "pdvprint.com.br",
    "nosh.com.br",
    "lojafsacajons.com.br",
    "revendedogs.com.br",
    "meseduza.com.br",
    "livelle.com.br",
    "segredodela.com.br",
    "anamayerlingerie.com",
    "br.ugg.com",
    "loja.medixbrasil.com.br",
    "casadasaliancas.com.br",
    "creditas.com",
    "super25.com.br",
    "continentalbrasil.com.br",
    "franciscajoias.com.br",
]
