import os

AMZ_STORE_NAME = os.getenv('AMZ_STORE_NAME')
BW2_AFL_ID = os.getenv('BW2_AFL_ID')
AFILIO_AFFID = os.getenv('AFILIO_AFFID')
AFILIO_TOKEN = os.getenv('AFILIO_TOKEN')
AFILIO_SITE_ID = os.getenv('AFILIO_SITE_ID')
MGZ_STORE_NAME = os.getenv('MGZ_STORE_NAME')
NATURA_CONSULTORIA_NAME = os.getenv('NATURA_CONSULTORIA_NAME')
BANGGOOD_REFERENCE_ID = os.getenv('BANGGOOD_REFERENCE_ID')
LOMADEE_SOURCE_ID = os.getenv('LOMADEE_SOURCE_ID')
ZANOX_ADS_SPACE_ID = os.getenv('ZANOX_ADS_SPACE_ID')
ZANOX_CONNECT_ID = os.getenv('ZANOX_CONNECT_ID')
